# Generated by Django 4.2.1 on 2023-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('sqr_feet', models.IntegerField()),
                ('no_bedrooms', models.IntegerField()),
                ('no_bathrooms', models.IntegerField()),
                ('adress', models.CharField(max_length=150)),
            ],
        ),
    ]
